### PR TITLE
Bump libui-node dep to 0.2.0-rc1

### PR DESCRIPTION
**Pull request by parro-it**
__NOT MEANT TO BE MERGED__

This PR bump libui-node to 0.2.0-rc1. 
This is a prerelease for version 0.2.0.
I wrote this PR to test the release before publish as npm latest.

It include PR #78 by @mischnic to test his new implementations on Area. 
@mischnic: I notice there are some part of the area.js example code commented: should they be working with your fixing on libui-node included in 0.2.0?

The 0.2.0 release will include:

* Add new event-loop example to test event loop stuff.
* Fixed setTimeout & setInterval.
* Other improvements to event loop code.
* Implemented binding for new `libui` text drawing API.
* Simplified binding.gyp file using dynamic inclusion of sources.
* Add -fvisibility flag in binding.gyp to allow using yoga & libui-node together.
* Fixed some memory leaks.
* Add linter check to C++ files.
* Fixed UiArea bugs & add missing bindings.
* Removing unneeded controls macro.
* Removing unneeded `nbind` workaround in UiArea.
* Fix event loop on macOS Sierra.

### CODE REVIEW

**Comment by mischnic** [comment]
> @mischnic: I notice there are some part of the area.js example code commented: should they be working with your fixing on libui-node included in 0.2.0?

Yes!

- `brush.type = 0 /*uiDrawBrushTypeSolid*/;`
- `const up = 0; //evt.getUp();`
- `//sp.free();`
- `//strokBrush.free();`
- `//fillBrush.free();`

**Comment by parro-it** [comment]
Would you mind updating your PR? I will then include here too...

**Comment by mischnic** [comment]
> Would you mind updating your PR? I will then include here too..

> **NOT MEAN TO BE MERGED**

Depending on how long this stays, the pr won't get merged because it would crash without updating libui-node as well. The only real (noticeable) change would be `const up = 0; //evt.getUp();` (= the `onMouseUp` event doesn't work).

**Comment by parro-it** [comment]
Anyone other got a change to test this? 
I'm going to publish 0.2.0 final if there no counter-arguments...

**Comment by parro-it** [comment]
I published version 0.2.0 of libui-node and wrote a PR that change the dependency version: #125

**Pull request closed without merging**
