### PR TITLE
Add min and max for slider

### LINKED ISSUE #131: min/max for Slider
e.g. `<Slider min={5} max={20}/>`

### PR DESCRIPTION
**Pull request by kusti8**
Fixes #131. Had to do some weird stuff, mainly removing all the children of the Slider's parent in libui, remaking the slider, and then adding back all of those children, which I want to test more thoroughly before I merge.

### CODE REVIEW

**Comment by mischnic** [comment]
This doesn't work:

```jsx
import React, { Component } from 'react';

import { render, Window, App, Slider, Box, Button, Text } from './src/';

class Example extends Component {
  state = { min: 20, max: 40, v: 10 };
  render() {
    return (
      <App>
        <Window title="Test" size={{ w: 500, h: 500 }} margined>
          <Box padded>
            <Slider stretchy={false} value={this.state.min} onChange={v => this.setState({min: v})}/>
            <Slider stretchy={false} value={this.state.max} onChange={v => this.setState({max: v})}/>
            <Slider stretchy={false} value={this.state.v} min={this.state.min} max={this.state.max} onChange={v => this.setState({v})}/>
            <Text>{String(this.state.v)}</Text>
            <Button stretchy={false} onClick={() => this.setState({ min: 10 })}>Reset</Button>
          </Box>
        </Window>
      </App>
    );
  }
}

render(<Example />);
```

**Comment by kusti8** [comment]
Ok I fixed the crash. It's a little annoying because it only goes one tick at a time for the min and max sliders (because it redraws everything which allows the sliders to lose focus), but I don't think there's an easy way to fix that. To fix it, you would have to know once the mouse click has been released and settled on a number, which currently with libui seems impossible.

**Comment by kusti8** [comment]
I didn't notice that. Fixed

**Comment by mischnic** [comment]
```
this.element.value = this.props.value; // put back the previous value, since this.element.value gets reset
```
It needs to be checked if the value is now smaller or larger than `min`/`max`.

slider

**Comment by kusti8** [comment]
Thanks! Fixed

**Pull request merged**
