### PR TITLE
More Area features

### PR DESCRIPTION
**Pull request by mischnic**
- Scrolling area:
```jsx
 <Area scrolling={{ w: 550, h: 1300 }}>
  <Area.Text>{ipsum}</Area.Text>
</Area>
```
- Gradients
```jsx
const linearGradient = Area.Gradient.createLinear(20, 20, 90, 90, {
  0: 'red',
  1: 'blue',
});

<Area.Rectangle x="10" y="10" width="100" height="100" fill={linearG}/>
```

Part of #130

### CODE REVIEW

**Comment by mischnic** [comment]
@kusti8 You might want to look into why the cover page of the docs always shows a random background color and displays `color)` as text at the bottom.

**Comment by mischnic** [comment]
Should fill/strokeOpacity be ignored for gradient?
```jsx
<Area.Rectangle
  stroke={linearGradient}
  strokeWidth="20"
  />
```
Otherwise, the gradient would have to be modified or copied on every render to update the alpha value.

**Comment by kusti8** [comment]
Thanks! Yeah you can ignore fill/strokeOpacity as long as it is noted. I guess docsify changed their api, so I have to go and fix that.

**Comment by kusti8** [comment]
Seems like docsify had a bug about rendering spaces in markdown: https://github.com/docsifyjs/docsify/issues/681. For now, I've moved back to 4.7.1

**Comment by kusti8** [comment]
It all looks nice! Thanks!

**Pull request merged**
