### PR TITLE
Add some Linux Pre-Req install steps

### PR DESCRIPTION
**Pull request by AustinBreslinDev**
Tried to create some install steps for Linux users. The steps include removing global nodejs conflicts installed from the package manager, removing global nodejs conflicts from using npm i -g, installing build-essential and libgtk-3-dev dependencies from package manager.

Steps only apply to Debian based flavours and would need to be altered for Arch based, Slack Based and RPM based flavours.

### CODE REVIEW

**Comment by kusti8** [comment]
I would rather not have a remove section. That should be up to the user, and as far as I know, that shouldn't be required.

**Comment by AustinBreslinDev** [comment]
It's incase they have installed node modules using the package manager, but I can remove it if you want. 

npm won't be able to remove them and they should be installed through npm and not the package manager.

Npm remove nome-gyp was added to remove a global version because it did seem to cause conflicts.

**Comment by kusti8** [comment]
I'd rather not have something like this. This should be left up to the user, as its very dependent on distro, and their own preferences. I've added build-essential to the pre-reqs. Node as a pre-req should be pretty obvious. Thanks!

**Comment by AustinBreslinDev** [comment]
To be honest I have been waiting for this pull request to be closed/completed so I could clean up my fork.

**Pull request closed without merging**
