### PR TITLE
Add yoga support. Fixes #67

### LINKED ISSUE #67: Add yoga layout support
I'd like to add yoga layout, because Grid is pretty buggy and it would make it more similar to React Native. There are a few things that need to be done to make this work. 

* [ ] Add fixed position support to libui (https://github.com/andlabs/libui/issues/306)
* [x] Add yoga-layout on the JS side
* [x] Create a wrapper called View over the libui Fixed widget

### PR DESCRIPTION
**Pull request by kusti8**
This is the PR that fixes #67.

It can't be merged right away because I still need libui support for GtkFixed and their equivalents on Windows and Mac, as well as sizing. Once that is done, which I'm going to work on now, then I can merge this. The API shouldn't change too much. If you're interested, I've added uiFixedAppend and uiFixedMove, as well as uiSize and uiSetSize. These are what need to be added to Windows and Mac and can be found on my libui and libui-node fork.

This currently supports full yoga layout, as far as I've tested. Meaning nested Views and all styling works. One thing that doesn't work is having a container such as a box as a child. You can't really mix yoga and stretchy layout. 

To test:
* Clone my [libui fork](https://github.com/kusti8/libui) and checkout the alpha3.5 fork (because libui-node currently only supports alpha3.5). This has my changes.
* `cd libui && mkdir build && cd build && cmake .. && make`
* Clone my [libui-node fork](https://github.com/kusti8/libui-node)
* Copy the header files in libui into libui-node root directory and the build/out/*.so files into the libui-node root directory also
* `cd libui-node && npm i`
* `sudo npm link`
* Clone proton-native and checkout the yoga branch
* `npm link libui-node`
* `npm i`
* `npm run demo`

### CODE REVIEW

**Comment by SkyzohKey** [comment]
Any update on this? 😇

**Comment by kusti8** [comment]
Currently, I need to merge a component into libui that allows fixed positioning, but I need to rewrite the GTK version, and its taking some research and time to do that.

**Comment by SkyzohKey** [comment]
What would be the stuffs to investigate with Gtk for this to progress, I have a long experience with it, may I help?

**Comment by mischnic** [comment]
@SkyzohKey This is the PR: https://github.com/andlabs/libui/pull/332.

These are the comments about GTK: https://github.com/andlabs/libui/pull/332#discussion_r179222384.

**Comment by hdev1** [comment]
Update on this?

**Comment by zaguiini** [comment]
👀

**Comment by kusti8** [comment]
Closing and rewriting in #213

**Pull request closed without merging**
