### PR TITLE
Use React event naming conventions

### PR DESCRIPTION
**Pull request by codediger**
In React, events are typically called onChange and onClick rather than onChanged and onClicked. Response to `gaearon` issue - Use React event naming conventions #9

### CODE REVIEW

**Comment by kusti8** [comment]
Have you confirmed that the methods are operational ? The code assumes that the libui-node methods and the props are the same, so I doubt that this will work. I would rather keep this consistent with libui-node

**Comment by mischnic** [comment]
> Works with existing React libraries such as Redux

What happens if other libraries use for example `onClick` instead of  `onClicked`?

**Comment by kusti8** [comment]
Yeah that's a good point. I can just do a object to map the names to libui names. I'm busy this week, but I can get it done next week.

**Comment by kusti8** [comment]
Closing this as it doesn't work. I'll follow this in #9

**Pull request closed without merging**
