### PR TITLE
Make hot reloading (and forceUpdate) work

### LINKED ISSUE #163: Root: Cannot read property 'setChild' of undefined
*Yes, this is an uncommon situation, but needed for hot reloading. A workaround would be fine as well.*

```
[HMR] TypeError: Cannot read property 'setChild' of undefined
    at Root.removeChild (.../proton-native/bin/components/DesktopComponent.js:83:36)
    at removeChildFromContainer (.../proton-native/bin/reconciler/index.js:82:20)
    at unmountHostComponents (.../proton-native/node_modules/react-reconciler/cjs/react-reconciler.development.js:6816:9)
    at commitDeletion (.../proton-native/node_modules/react-reconciler/cjs/react-reconciler.development.js:6863:5)
    at commitAllHostEffects (.../proton-native/node_modules/react-reconciler/cjs/react-reconciler.development.js:7445:11)
    at Object.invokeGuardedCallback$1 (.../proton-native/node_modules/react-reconciler/cjs/react-reconciler.development.js:1793:10)
    at invokeGuardedCallback (.../proton-native/node_modules/react-reconciler/cjs/react-reconciler.development.js:1938:29)
    at commitRoot (.../proton-native/node_modules/react-reconciler/cjs/react-reconciler.development.js:7595:7)
    at completeRoot (.../proton-native/node_modules/react-reconciler/cjs/react-reconciler.development.js:8645:34)
    at performWorkOnRoot (.../proton-native/node_modules/react-reconciler/cjs/react-reconciler.development.js:8589:9)
``` 

To reproduce it, paste the following code into `src/index.js` in [proton-hot-boilerplate](https://github.com/mischnic/proton-hot-boilerplate), run `npm run dev` and change something in `HotApp`'s children. The error occurs only when the code inside `if(module.hot.data && module.hot.data.proxy)` is run, not on the first render.
It also works when using `HotApp` directly without the `Wrapper` component as described in the comments:

```js
import React, { Component } from "react";
import { App, Window, render, Box, Button } from "proton-native";
import { createProxy } from "react-proxy";

class HotApp extends Component {
  render() {
    return (
      <App>
        <Window title="Notes" size={{ w: 500, h: 350 }} margined>
          <Button>Button</Button>
        </Window>
      </App>
    );
  }
}

class Wrapper extends Component {
  render() {
    return <HotApp />;
  }
}

if (module.hot) {
  let proxy;

  if (module.hot.data && module.hot.data.proxy) {
    // hot reload

    const mountedInstances = module.hot.data.proxy.update(Wrapper);
    // Works perfectly:
    // const mountedInstances = module.hot.data.proxy.update(HotApp);

    mountedInstances.forEach(i => i.forceUpdate());
  } else {
    // initial render

    proxy = createProxy(Wrapper);
    // Works perfectly:
    // proxy = createProxy(HotApp);

    render(React.createElement(proxy.get()));
  }

  // Please reload me
  module.hot.accept();
  // Make proxy available in updated module
  module.hot.dispose(data => {
    data.proxy = proxy || (module.hot.data && module.hot.data.proxy);
  });
} else {
  render(<Wrapper />);
}

```

### PR DESCRIPTION
**Pull request by kusti8**
I changed some core stuff here on how updates and rendering is handled, so I want to test it more before I merge. Fixes #163

### CODE REVIEW

**Comment by mischnic** [comment]
With the code from #163, it works fine for the first reload but on the second change, there is a warning:

```
2018-07-08 11:12:56.507 node[970:953350] get 0x0

Webpack Compiling...
Webpack    16 modules
Webpack Compiled successfully.
[HMR] Checking for updates...
[HMR] Updated modules:
[HMR]  - ./src/index.js
[HMR] App is up to date.

Webpack Compiling...
Webpack    16 modules
Webpack Compiled successfully.
[HMR] Checking for updates...
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in HotApp
[HMR] Updated modules:
[HMR]  - ./src/index.js
[HMR] App is up to date.
```

**Comment by kusti8** [comment]
What are you changing? I can't reproduce that

**Comment by mischnic** [comment]
> What are you changing? I can't reproduce that

Nevermind...

**Comment by kusti8** [comment]
Ok it seems to work pretty well so I'll merge for now.

**Comment by mischnic** [comment]
When are you planning to do the next release?

**Comment by kusti8** [comment]
Yeah sorry about that. I'll release tomorrow.

**Comment by kusti8** [comment]
Done

**Pull request merged**
