### PR TITLE
feat: add size getters to the Area component

### PR DESCRIPTION
**Pull request by maciek134**
This adds the ability to query `<Area>`'s size as mentioned in #130. Also modified the area example to show how to use it.

### CODE REVIEW

**Comment by kusti8** [comment]
That actually seems like the easiest solution. The documentation will need to be changed however. Could you do this?

**Comment by mischnic** [comment]
I'm (currently) unable to implement my approach, but I still don't think this is very elegant (especially because this requires setting the size in the state manually).
This would be the first use of refs in proton-native (though libui exposes also a scrollTo function for scrolling areas which would need this)

**Comment by mischnic** [comment]
> You don't need to set it in the state, I did it so the UI would be updated

What would would you do otherwise if not update the UI?

> That actually seems like the easiest solution

Easiest to implement, yes. But easiest to use?

Using refs:
```jsx
class Example extends Component {
  state = {
    rectangleWidth: 100
  };

  constructor(props) {
    super(props);
    this.area = React.createRef();
    this.onContentSizeChange = this.onContentSizeChange.bind(this);
  }

  onContentSizeChange() {
    this.setState({
      rectangleWidth: Math.pow(this.area.current ? this.area.current.getWidth() : 100, 2)
    });
  }

  render() {
    return (
      <App>
        <Window
          title="Test"
          size={{ w: 600, h: 650 }}
          margined={true}
          onContentSizeChange={this.onContentSizeChange}
        >
          <Box padded>
            <Area
              ref={this.area}
            >
	            <Area.Rectangle
	              x="100"
	              y="0"
	              width={this.state.rectangleWidth}
	              height="100"
	              fill="blue"
	            />
            </Area>
          </Box>
        </Window>
      </App>
    );
  }
}
```

Function as children approach (if it works):
```jsx
class Example extends Component {
  render() {
    return (
      <App>
        <Window
          title="Test"
          size={{ w: 600, h: 650 }}
          margined={true}
        >
          <Box padded>
            <Area>
              {(width, height) => (
                <Area.Rectangle
                  x="100"
                  y="0"
                  width={Math.pow(width, 2)}
                  height="100"
                  fill="blue"
                />
              )}
            </Area>
          </Box>
        </Window>
      </App>
    );
  }
}

```

**Comment by maciek134** [comment]
If you want to write everything in JSX I have no more arguments. @kusti8 will have to make the _executive decision_ here.

Your idea is specific for just rendering, mine works for every use case. You have to force a re-render to get the new size, I just get the event and decide if the re-render is needed. Simple example from the editor component I'm writing: the user changes the horizontal size of the window - the number of lines shown doesn't change so I don't need to re-render the whole component.

The only other way to do this is to create a callback like `onContentSizeChange` but for Area. Not a good idea since you can't really detect that the area changed size in libui, but on the other hand it can be patched later if support for such thing is added to libui, and for now we can just traverse the component tree up until we find a Window and attach the callback there.

**Comment by mischnic** [comment]
> the user changes the horizontal size of the window - the number of lines shown doesn't change so I don't need to re-render the whole component.

A resize always triggers a area redraw, otherwise there would be nothing drawn in the previously not visible area part.

> Your idea is specific for just rendering, mine works for every use case. 

But mine feels way more natural for drawing.

> change the PR after I get back.

I can totally live with `Area.onSizeChange`. And these two aren't mutually exclusive, so the function as children could still be added?

**Comment by maciek134** [comment]
Area redraw - yes, React component re-render - no. There is a big difference there. Why do you want to add these functions so much? It's not how it's done in React, that's why you get the warning and there is no way around that, save for dirty hacks.

**Comment by mischnic** [comment]
> React component re-render - no.

AreaComponent don't render like React components, their render methods get called in the area callback.

> It's not how it's done in React, that's why you get the warning and there is no way around that, save for dirty hacks.

There will be no dirty hacks.

**Comment by maciek134** [comment]
Can you please re-read what I wrote? And if you look at the source code, the internal area is not drawn like a React component, but the one you use in the app (`react-components/Area`) is.

About dirty hacks - we will see, but the warning is there for a reason.

**Comment by maciek134** [comment]
@kusti8 changed to `onSizeChanged` event instead of ref/getters.

**Comment by mischnic** [comment]
`AreaComponent`s are the possible children of Area: `Area.Rectangle, Area.Circle, Area.Text, ...`

>  the internal area is not drawn like a React component, but the one you use in the app (react-components/Area) is.

Why do you want to re-render the Area component? This would only affect the children (`AreaCompontent`s).
And react-components/Area does only this:
```jsx
render (){
	return <AreaContext.Provider> {/*For StyledText to work*/}
		<AreaInternal {...areaProps}>
			<Area.Group {...areaGroupProps}>
				{this.props.children}
			</Area.Group>
		</AreaInternal>
	</AreaContext.Provider>;
}
```

> but the warning is there for a reason.

Only because I didn't really know what I was doing. This will be fixed properly and as it's supposed to work, or not at all.

**Comment by maciek134** [comment]
Because with your approach you have to re-render the `Area` component to get new width/height values, don't you know how/when the render function is called in React?

**Comment by maciek134** [comment]
@mischnic Since there is no documentation for libui I didn't know you got an event when the area was resized, that's why I used refs. And just for clarity, you seem to have omitted a very important line when quoting the docs:

> For example, instead of exposing open() and close() methods on a Dialog component, pass an isOpen prop to it.

Which is exactly what I've done after I learned it was possible. Your approach on the other hand is nowhere to be found in React/RN. You keep proposing things that are complex and inefficient just for the sake of doing it your way. As someone who has been using React almost since day one if I saw any of the things you proposed in the docs I'd just pass on this library.

**Comment by mischnic** [comment]
Should onSizeChange expose the libui area object? The other callbacks don't do that (the defaultProps declaration for them is wrong but the docs are correct).

**Comment by kusti8** [comment]
I was wondering about that since the default props for the others did it
also. It shouldn't expose libui.

**Comment by maciek134** [comment]
Should I fix only this or add another commit that fixes the default props for others as well?

**Comment by kusti8** [comment]
Fix the others as well while we're at it. Thanks!

**Comment by kusti8** [comment]
I fixed the default props and the area example and it seems to work fine on my end. I'll merge tomorrow if everything is good.

**Comment by mischnic** [comment]
There is one issue with this: you can't determine the size of the initial render:

bildschirmfoto 2018-11-01 um 18 27 48

**Pull request merged**
