### PR TITLE
Add travis ci support

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by mischnic** [comment]
Quite pointless without running any tests...

**Comment by kusti8** [comment]
All your addition does is run Babel, which is not a test. Testing is discussed in #165 and until that is done, there is no use for Travis.

**Comment by amilajack** [comment]
Why close this then? Shouldn't this be open until that issue is resolved?

**Comment by kusti8** [comment]
When testing is done, which depends on libui-napi currently, then I can easily add Travis myself once it test it thoroughly. It doesn't make sense to split the discussion and to try and predict how it will work before it is done.

**Pull request closed without merging**
