### PR TITLE
Removed bin folder from git

### PR DESCRIPTION
**Pull request by parro-it**
I removed the built folder bin from git, as discussed in #57

### CODE REVIEW

**Comment by mischnic** [comment]
Missing: 

- replace JSX in 
```
src/react-components/Box.js
src/react-components/Menu.js
src/react-components/Picker.js
src/react-components/RadioButtons.js
src/react-components/Separator.js
src/react-components/TextInput.js
````
with "normal" instantiation.

- change bin to src:
https://github.com/kusti8/proton-native/blob/57896ffed96188a40328b4239858a110f395b1f6/package.json#L5

**Comment by parro-it** [comment]
We can also keep the babel build phase and publish the `bin` only on `npm` (and src only on GH)

**Comment by mischnic** [comment]
>The problem then is that the git repository itself won't work as a dependency in package.json, because the source files need to be transpiled first.

(https://github.com/kusti8/proton-native/pull/57#issuecomment-374368531)

**Comment by parro-it** [comment]
> The problem then is that the git repository itself won't work as a dependency in package.json, because the source files need to be transpiled first.

Why that's a problem? Ideally, it should be included from npm

**Comment by mischnic** [comment]
> > The git repo shouldn't be a dependency anyway
>
> Its useful for development, like you did with your forked libui-node.

(https://github.com/kusti8/proton-native/pull/57#issuecomment-374370606)

But by fixing the JSX, recent node versions will work fine.

**Comment by parro-it** [comment]
> The problem then is that the git repository itself won't work as a dependency in package.json, because the source files need to be transpiled first.

And anyway, I would prefer to remove the build phase too... just thinking about the two possibility

**Comment by parro-it** [comment]
We have to remove all the es6 imports too...

**Comment by mischnic** [comment]
Oh, didn't think about that. Two options:
- change them into requires
- not git dependency

@kusti8 What do you think? Is the git package dependency needed?

**Comment by parro-it** [comment]
`@std/esm` could also be an option, at least until node 10 ships (on April I think) that will support es6 modules   without any flag.

**Comment by kusti8** [comment]
I'd rather not add another dependency such as esm just for this. I would just remove the bin folder and not have git as a dependency. It would be nice to have, but code readability and usability should come first.

**Comment by parro-it** [comment]
Fine, so I think this PR could be merged as-is. Or if you prefer, I can also add necessary changes to package.json to publish only the `bin` folder.

**Pull request merged**
